---

#default redis config
cache_config_defaults: &CACHE_DEFAULTS
  background:
    writeback_goroutines: 20
  redis:
    endpoint: "redis:6379"
  fifocache:
    max_size_bytes: 128MB
    max_size_items: 100
    ttl: 1h0m0s
    purgeinterval: 10s

loki_config_server:
  # log_level: debug
  http_listen_address: "127.0.0.1"
  http_listen_port: 3100
  http_server_write_timeout: 10m
  http_server_read_timeout: 10m
  http_server_idle_timeout: 10m
  grpc_server_max_send_msg_size: 8388608
  grpc_server_max_recv_msg_size: 8388608
  graceful_shutdown_timeout: 2m

loki_config_distributor:
  ring:
    kvstore:
      store: inmemory
    heartbeat_timeout: 30s

loki_config_compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  compactor_ring:
    kvstore:
      store: inmemory

loki_config_querier:
  engine:
    timeout: 5m
    max_look_back_period: 30s
  query_timeout: 30m
  query_ingesters_within: 10m
  max_concurrent: 20

loki_config_query_scheduler:
  # instance_id: "{{ ansible_hostname }}"
  # use_scheduler_ring: true
  scheduler_ring:
    heartbeat_timeout: 10s
    kvstore:
      store: inmemory

loki_config_ingester_client:
  pool_config:
    client_cleanup_period: 30s
    health_check_ingesters: true

loki_config_ingester:
  chunk_encoding: snappy
  chunk_idle_period: 30m
  chunk_block_size: 2621440
  chunk_retain_period: 1m
  max_chunk_age: 120m
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

loki_config_limits:
  max_entries_limit_per_query: 0
  ingestion_rate_strategy: global
  reject_old_samples: false
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 100
  max_cache_freshness_per_query: 10m
  creation_grace_period: 1m
  enforce_metric_name: false
  reject_old_samples_max_age: 12h
  max_query_parallelism: 900
  max_query_series: 1000
  increment_duplicate_timestamp: true

loki_config_storage:
  index_cache_validity: 10m0s
  disable_broad_index_queries: true
  index_queries_cache_config:
    <<: *CACHE_DEFAULTS

loki_config_chunk_store:
  # store for 1 year
  max_look_back_period: 8760h
  chunk_cache_config:
    <<: *CACHE_DEFAULTS

loki_config_schema:
  configs:
    - from: "2020-10-24"
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
        tags:
          foo: bar
          year: 2020
      chunks:
        prefix: index_
        period: 168h
      row_shards: 16

loki_config_common:
  storage:
    filesystem:
      rules_directory: "{{ loki_storage_dir }}/rules"
      chunks_directory: "{{ loki_storage_dir }}/chunks"

loki_config_query_range:
  align_queries_with_step: true
  parallelise_shardable_queries: true
  max_retries: 5
  cache_results: true
  results_cache:
    # https://grafana.com/docs/loki/latest/configuration/#cache_config
    cache:
      <<: *CACHE_DEFAULTS

loki_config_frontend:
  log_queries_longer_than: 10s
  compress_responses: true
  max_outstanding_per_tenant: 2048
  # tail_proxy_url: "http://{{ ansible_hostname }}:3100"

loki_config_frontend_worker:
  parallelism: 4
  grpc_client_config:
    # 16GiB
    max_send_msg_size: 17179869184
    max_recv_msg_size: 17179869184

# loki_config_memberlist:
#   abort_if_cluster_join_fails: false
#   # Expose this port on all distributor, ingester
#   # and querier replicas.
#   bind_port: 7946
#   join_members:
#     - "{{ ansible_hostname }}:7946"
#   max_join_backoff: 1m
#   max_join_retries: 10
#   min_join_backoff: 1s

...
